---
resources:
  - name: repo
    type: git
    source:
      uri: https://git.kun.is/pim/concourse-apprise-notifier.git
    icon: git
  - name: registry-image
    type: registry-image
    source:
      repository: git.kun.is/pim/concourse-apprise-notifier
      username: pim
      password: ((api_key))
      tag: stable
    icon: docker
  - name: version
    type: semver
    source:
      driver: git
      initial_version: "1.1.0"
      uri: ssh://git@git.kun.is:56287/pim/concourse-apprise-notifier.git
      branch: version
      file: version
      private_key: {{private_key}}
    icon: numeric

jobs:
  - name: build-and-publish-image
    plan:
      - get: repo
        trigger: true
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: repo
          outputs:
            - name: image
          params:
            DOCKERFILE: repo/Dockerfile
            LABELS_FILE: repo/labels
          run:
            path: sh
            args:
              - -exc 
              - |
                build
                ls image
      - get: version
        params:
          bump: patch
      - put: registry-image
        params:
          image: image/image.tar
          additional_tags: version/version
      - put: version
        params:
          file: version/version
