---
resources:
  - name: repo
    type: git
    source:
      uri: https://git.pim.kunis.nl/pim/concourse-apprise-notifier.git
    icon: git
  - name: registry-image
    type: registry-image
    source:
      repository: git.pim.kunis.nl/pim/concourse-apprise-notifier
      username: pim
      password: ((api_key))
      tag: ((image_version))
    icon: docker

jobs:
  - name: build-and-publish-image
    plan:
      - get: repo
        trigger: true
      - task: build-image
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: concourse/oci-build-task
          inputs:
            - name: repo
          outputs:
            - name: image
          params:
            DOCKERFILE: repo/Dockerfile
            LABELS_FILE: repo/labels
          run:
            path: sh
            args:
              - -exc 
              - |
                build
                ls image
      - put: registry-image
        params:
          image: image/image.tar
